class CSPTemplate:
    main_csp = """-- the following two files are generated by python script
include "$attack_tree_csp"
include "$test_cases_csp"

channel attack_succeed
Attack_End = attack_succeed -> STOP

Test_Purpose = Attacker ; Attack_End

SystemEvents = diff(Events, {attack_succeed})

UnsecureSystem = RUN(SystemEvents)

assert UnsecureSystem [] Test_Cases [T= UnsecureSystem [| SystemEvents |] Test_Purpose
"""

